services:
  tutorial:
    hostname: accelforge
    image: accelforge/accelforge-infrastructure
    ports:
      - 8888:8888
    volumes:
      - ./:/home/workspace
    stdin_open: true # docker run -i
    tty: true        # docker run -t
